export const languageCodes = [
  "pt-BR", // Portuguese (Brazil)
  "pt", // Portuguese
  "en", // English
  "es", // Spanish
  "fr", // French
  "de", // German
  "it", // Italian
  "zh", // Chinese
  "ja", // Japanese
  "ar", // Arabic
  "ru", // Russian
  "hi", // Hindi
  "ko", // Korean
  "tr", // Turkish
  "nl", // Dutch
  "sv", // Swedish
  "pl", // Polish
  "da", // Danish
  "fi", // Finnish
  "no", // Norwegian
  "cs", // Czech
  "el", // Greek
  "he", // Hebrew
  "th", // Thai
  "hu", // Hungarian
  "id", // Indonesian
  "ms", // Malay
  "vi", // Vietnamese
  "bg", // Bulgarian
  "ro", // Romanian
  "uk", // Ukrainian
  "fa", // Persian
  "bn", // Bengali
  "ta", // Tamil
  "te", // Telugu
  "mr", // Marathi
  "kn", // Kannada
  "ml", // Malayalam
  "pa", // Punjabi
  "gu", // Gujarati
  "or", // Odia
  "sa", // Sanskrit
  "ur", // Urdu
  "sw", // Swahili
  "af", // Afrikaans
  "ka", // Georgian
  "sr", // Serbian
  "hr", // Croatian
  "sl", // Slovenian
  "sk", // Slovak
  "lt", // Lithuanian
  "lv", // Latvian
  "et", // Estonian
  "is", // Icelandic
  "ga", // Irish
  "cy", // Welsh
  "eu", // Basque
  "ca", // Catalan
  "gl", // Galician
  "mt", // Maltese
  "sq", // Albanian
  "mk", // Macedonian
  "bs", // Bosnian
  "mn", // Mongolian
  "kk", // Kazakh
  "uz", // Uzbek
  "tk", // Turkmen
  "ky", // Kyrgyz
  "tg", // Tajik
  "hy", // Armenian
  "az", // Azerbaijani
  "la", // Latin
];
